linters:
  # Use default linters plus these extras
  enable:
    - golint
    - gofmt
    - goimports
    - unconvert
    - unparam
    - gocritic
    - gochecknoglobals
    - nakedret
    - misspell
