linters:
  # Use default linters plus these extras
  enable:
    - golint
    - gofmt
    - goimports
    - unconvert
    - unparam
    - gocritic

service:
  golangci-lint-version: 1.22.x # use the fixed version to not introduce new linters unexpectedly
