linters:
  # Use default linters plus these extras
  enable:
    - golint
    - gofmt
    - goimports
    - unconvert
    - unparam
    - gocritic
    - gochecknoglobals
    - nakedret
    - misspell

service:
  golangci-lint-version: 1.21.x # use the fixed version to not introduce new linters unexpectedly
