before:
  hooks:
  - go mod tidy
archives:
- replacements:
    # give a more user friendly name to macOS
    darwin: macOS
  # Make Windows archives .zip, not .tar.gz
  format_overrides:
  - goos: windows
    format: zip
builds:
- env:
  # Goreleaser doesnt support CGO
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
checksum:
  # Use a simpler name than the default
  name_template: 'checksums.txt'
changelog:
  skip: true
